//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho
{
    using System;
    using System.Collections.Generic;
    
    public partial class FATO
    {
        public decimal Idf_Fato { get; set; }
        public decimal Idf_Regiao { get; set; }
        public decimal Idf_Tempo { get; set; }
        public decimal Idf_Imovel { get; set; }
    
        public virtual Imovel Imovel { get; set; }
        public virtual Regiao Regiao { get; set; }
        public virtual Tempo Tempo { get; set; }
    }
}
