//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_Fato
    {
        public decimal Idf_Fato { get; set; }
        public decimal Idf_Bairro { get; set; }
        public decimal Idf_Tempo { get; set; }
        public decimal Idf_Imovel { get; set; }
        public string Padrao { get; set; }
    
        public virtual TAB_Bairro TAB_Bairro { get; set; }
        public virtual TAB_Imovel TAB_Imovel { get; set; }
        public virtual TAB_Tempo TAB_Tempo { get; set; }
    }
}
