//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_Cidade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAB_Cidade()
        {
            this.TAB_Bairro = new HashSet<TAB_Bairro>();
        }
    
        public decimal Idf_Cidade { get; set; }
        public decimal Idf_Estado { get; set; }
        public string Des_Cidade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_Bairro> TAB_Bairro { get; set; }
        public virtual TAB_Estado TAB_Estado { get; set; }
    }
}
