//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tempo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tempo()
        {
            this.FATO = new HashSet<FATO>();
        }
    
        public decimal Idf_Tempo { get; set; }
        public Nullable<decimal> Analise_Mensal { get; set; }
        public string Clima { get; set; }
        public Nullable<decimal> Semana_Mes { get; set; }
        public Nullable<bool> Flg_Feriado { get; set; }
        public Nullable<bool> Flg_Final_Semana { get; set; }
        public Nullable<decimal> Mes_Ano { get; set; }
        public Nullable<System.DateTime> Data_Dia { get; set; }
        public string Estacao_Ano { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FATO> FATO { get; set; }
    }
}
