//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrabalhoEFEntities : DbContext
    {
        public TrabalhoEFEntities()
            : base("name=TrabalhoEFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TAB_Bairro> TAB_Bairro { get; set; }
        public virtual DbSet<TAB_Cidade> TAB_Cidade { get; set; }
        public virtual DbSet<TAB_Estado> TAB_Estado { get; set; }
        public virtual DbSet<TAB_Fato> TAB_Fato { get; set; }
        public virtual DbSet<TAB_Imovel> TAB_Imovel { get; set; }
        public virtual DbSet<TAB_Tempo> TAB_Tempo { get; set; }
    }
}
