//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrabalhoEFEntities : DbContext
    {
        public TrabalhoEFEntities()
            : base("name=TrabalhoEFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bairro> Bairro { get; set; }
        public virtual DbSet<Cidade> Cidade { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<FATO> FATO { get; set; }
        public virtual DbSet<Imovel> Imovel { get; set; }
        public virtual DbSet<Regiao> Regiao { get; set; }
        public virtual DbSet<Tempo> Tempo { get; set; }
    }
}
